FROM swift:5.7.1-focal as builder

RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && apt-get -q update && \
    apt-get install -y \
    libjavascriptcoregtk-4.0-dev \
    unzip

WORKDIR /root/Transom
COPY ./dist ./dist
COPY ./Package.resolved ./Package.resolved
COPY ./Package.swift ./Package.swift
COPY ./Plugins ./Plugins
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN swift package reset
RUN swift build --configuration release

FROM fedora:37

WORKDIR /root/Transom
COPY --from=builder /root/Transom/.build/release/TransomTool-focal .
COPY --from=builder /root/Transom/.build/release/TransomTool-focal .
