FROM swift:5.7.1-amazonlinux2 as builder

RUN yum install -y \
    libatomic1 \
    webkitgtk4-jsc-devel \
    unzip

WORKDIR /root/Transom
COPY ./.build/repositories ./.build/repositories
COPY ./.git ./.git
COPY ./dist ./dist
COPY ./Package.resolved ./Package.resolved
COPY ./Package.swift ./Package.swift
COPY ./Plugins ./Plugins
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN swift package resolve
RUN swift build --configuration release

FROM swift:5.7.1-amazonlinux2

WORKDIR /root/Transom
COPY --from=builder /root/Transom/.build/release/TransomTool-focal .
COPY --from=builder /root/Transom/.build/release/TransomTool-focal .
