FROM fedora:38 as builder

RUN dnf install -y \
    git \
    unzip \
    swift-lang-5.7.3-2.fc38 \
    javascriptcoregtk4.1-devel \
    libatomic_ops
    
RUN ln -s /usr/libexec/swift/*/lib/libsourcekitdInProc.so /usr/lib/libsourcekitdInProc.so

WORKDIR /root/Transom
COPY ./.build/repositories ./.build/repositories
COPY ./.git ./.git
COPY ./dist ./dist
COPY ./Package.resolved ./Package.resolved
COPY ./Package.swift ./Package.swift
COPY ./Plugins ./Plugins
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN swift package resolve
RUN swift build --configuration release

FROM fedora:38

WORKDIR /root/Transom
COPY --from=builder /root/Transom/.build/release/TransomTool .
COPY --from=builder /root/Transom/.build/release/TransomTool .
